# Generated by Django 5.0.7 on 2024-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_task_category_task_next_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Unsure', 'Unsure'), ('Health', 'Health'), ('Finance', 'Finance'), ('Hobby', 'Hobby'), ('Urgent', 'Urgent'), ('Learning', 'Learning'), ('Social', 'Social')], default='Unsure', max_length=20),
        ),
    ]
